In [1]:
%matplotlib inline


What is PyTorch?
================

Python 기반의 과학 연산 패키지로 다음과 같은 두 집단을 대상으로 합니다:

-  NumPy를 대체하면서 GPU를 이용한 연산이 필요한 경우
-  최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

Getting Started
---------------

Tensor는 NumPy의 ndarray와 유사하며, 추가로 GPU를 사용한 연산 가속도 가능합니다.



In [2]:
from __future__ import print_function
import torch

torch.__version__

'1.9.0'

초기화되지 않은 5x3 행렬을 생성합니다:



In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[9.1837e-39, 4.6837e-39, 9.9184e-39],
        [9.0000e-39, 1.0561e-38, 1.0653e-38],
        [4.1327e-39, 8.9082e-39, 9.8265e-39],
        [9.4592e-39, 1.0561e-38, 1.0653e-38],
        [1.0469e-38, 9.5510e-39, 1.0745e-38]])


무작위로 초기화된 행렬을 생성합니다:



In [5]:
x = torch.randn(5, 3)
print(x)
x = torch.rand(5, 3)
print(x)

tensor([[-0.9269, -0.1611,  1.3244],
        [-0.8558, -1.1958,  0.7805],
        [-0.2680, -0.8735, -0.2883],
        [-0.7274, -0.7406,  0.5552],
        [ 0.7556,  1.6970, -0.8218]])
tensor([[0.9414, 0.8470, 0.0647],
        [0.2688, 0.3427, 0.5918],
        [0.9950, 0.4475, 0.1020],
        [0.9988, 0.4139, 0.8519],
        [0.6713, 0.9859, 0.2296]])


dtype이 long이고 0으로 채워진 행렬을 생성합니다:



In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.ones(5, 3, dtype=torch.long)
print(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


데이터로부터 tensor를 직접 생성합니다:



In [8]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


또는 존재하는 tensor를 바탕으로 tensor를 만듭니다. 
이 메소드(method)들은 사용자로부터 제공된 새로운 값이 없는 한, 입력 tensor의 속성들(예. dtype)을 재사용합니다.


In [10]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.8247,  1.4181,  0.7263],
        [-0.3876, -1.2666, -0.3987],
        [-1.0244, -1.3771,  1.4353],
        [-0.3911, -0.1165,  0.0386],
        [ 1.0255, -0.4024,  0.0377]])


행렬의 크기를 구합니다:



In [11]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])



덧셈: 문법1

In [12]:
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

tensor([[ 0.8247,  1.4181,  0.7263],
        [-0.3876, -1.2666, -0.3987],
        [-1.0244, -1.3771,  1.4353],
        [-0.3911, -0.1165,  0.0386],
        [ 1.0255, -0.4024,  0.0377]])
tensor([[0.8876, 0.9805, 0.8041],
        [0.3443, 0.8596, 0.3013],
        [0.1146, 0.7188, 0.9739],
        [0.8891, 0.3346, 0.1639],
        [0.7310, 0.1610, 0.4929]])
tensor([[ 1.7122,  2.3986,  1.5304],
        [-0.0433, -0.4070, -0.0974],
        [-0.9099, -0.6583,  2.4092],
        [ 0.4980,  0.2181,  0.2024],
        [ 1.7565, -0.2414,  0.5306]])


덧셈: 문법2



In [13]:
print(torch.add(x, y))

tensor([[ 1.7122,  2.3986,  1.5304],
        [-0.0433, -0.4070, -0.0974],
        [-0.9099, -0.6583,  2.4092],
        [ 0.4980,  0.2181,  0.2024],
        [ 1.7565, -0.2414,  0.5306]])


덧셈: 결과 tensor를 인자로 제공


In [14]:
result = torch.empty(5, 3)
print(result)

torch.add(x, y, out=result)
print(result)

tensor([[ 1.7122,  2.3986,  1.5304],
        [-0.0433, -0.4070, -0.0974],
        [-0.9099, -0.6583,  2.4092],
        [ 0.4980,  0.2181,  0.2024],
        [ 1.7565, -0.2414,  0.5306]])
tensor([[ 1.7122,  2.3986,  1.5304],
        [-0.0433, -0.4070, -0.0974],
        [-0.9099, -0.6583,  2.4092],
        [ 0.4980,  0.2181,  0.2024],
        [ 1.7565, -0.2414,  0.5306]])


덧셈: 바꿔치기(In-place) 방식


In [16]:
# adds x to y
print(y)
print()
y.add(x)
print('use add()')
print(y)
print()
y.add_(x)
print('use add_()')
print(y)

tensor([[ 1.7122,  2.3986,  1.5304],
        [-0.0433, -0.4070, -0.0974],
        [-0.9099, -0.6583,  2.4092],
        [ 0.4980,  0.2181,  0.2024],
        [ 1.7565, -0.2414,  0.5306]])

use add()
tensor([[ 1.7122,  2.3986,  1.5304],
        [-0.0433, -0.4070, -0.0974],
        [-0.9099, -0.6583,  2.4092],
        [ 0.4980,  0.2181,  0.2024],
        [ 1.7565, -0.2414,  0.5306]])

use add_()
tensor([[ 2.5369,  3.8167,  2.2566],
        [-0.4309, -1.6736, -0.4961],
        [-1.9343, -2.0354,  3.8444],
        [ 0.1069,  0.1016,  0.2410],
        [ 2.7820, -0.6438,  0.5682]])


<div class="alert alert-info"><h4>Note</h4><p>바꿔치기(In-place) 방식으로 tensor의 값을 변경하는 연산은 _ 를 접미사로 갖습니다.<p>
예: x.copy_(y), x.t_() 는 x 를 변경합니다.

<p>
NumPy스러운 인덱싱 표기 방법을 사용할 수도 있습니다!


In [17]:
print(x)
print(x[:, 1])

tensor([[ 0.8247,  1.4181,  0.7263],
        [-0.3876, -1.2666, -0.3987],
        [-1.0244, -1.3771,  1.4353],
        [-0.3911, -0.1165,  0.0386],
        [ 1.0255, -0.4024,  0.0377]])
tensor([ 1.4181, -1.2666, -1.3771, -0.1165, -0.4024])


크기 변경: tensor의 크기(size)나 모양(shape)을 변경하고 싶다면 torch.view 를 사용합니다:


In [18]:
x = torch.randn(4, 4)
print(x)

y = x.view(16)
z = y.view(-1, 2)  # the size -1 is inferred from other dimensions
print(y)
print(z)
print(y.size(), z.size())

tensor([[ 0.0928,  0.9503, -0.8155, -1.0648],
        [-1.0021,  1.0810, -0.3547,  1.3357],
        [-1.6322, -0.6710, -0.7433, -0.3438],
        [ 0.2899,  0.1822, -0.2444, -0.8420]])
tensor([ 0.0928,  0.9503, -0.8155, -1.0648, -1.0021,  1.0810, -0.3547,  1.3357,
        -1.6322, -0.6710, -0.7433, -0.3438,  0.2899,  0.1822, -0.2444, -0.8420])
tensor([[ 0.0928,  0.9503],
        [-0.8155, -1.0648],
        [-1.0021,  1.0810],
        [-0.3547,  1.3357],
        [-1.6322, -0.6710],
        [-0.7433, -0.3438],
        [ 0.2899,  0.1822],
        [-0.2444, -0.8420]])
torch.Size([16]) torch.Size([8, 2])


만약 tensor에 하나의 값만 존재한다면, .item() 을 사용하면 숫자 값을 얻을 수 있습니다.



In [19]:
x = torch.randn(1)
print(x)
print(type(x), type(x.item()))
print(x.item())


tensor([-0.4287])
<class 'torch.Tensor'> <class 'float'>
-0.4287288784980774


**읽을 거리:**


  전치(transposing), 인덱싱(indexing), 슬라이싱(slicing), 수학 계산, 선형 대수, 난수(random number) 등과 같은 100가지 이상의 Tensor 연산은
  `여기 <http://pytorch.org/docs/torch>` 에 설명되어 있습니다.

NumPy 변환(Bridge)
------------

Torch Tensor를 NumPy 배열(array)로 변환하거나, 그 반대로 하는 것은 매우 쉽습니다.

(CPU 상의) Torch Tensor와 NumPy 배열은 저장 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.

- Torch Tensor를 NumPy 배열로 변환하기



In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


NumPy 배열의 값이 어떻게 변하는지 확인해보세요.



In [22]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [23]:
temp = a.clone()
temp_numpy = temp.numpy()

a.add_(1)
print(a)
print(temp_numpy)

tensor([3., 3., 3., 3., 3.])
[2. 2. 2. 2. 2.]


 - NumPy 배열을 Torch Tensor로 변환하기  
 
NumPy(np) 배열을 변경하면 Torch Tensor의 값도 자동 변경되는 것을 확인해보세요.



In [24]:
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)


[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


CharTensor를 제외한 CPU 상의 모든 Tensor는 NumPy로의 변환을 지원하며, (NumPy에서 Tensor로의) 반대 변환도 지원합니다.

CUDA Tensors
------------

.to 메소드를 사용하여 Tensor를 어떠한 장치로도 옮길 수 있습니다.



In [22]:
import torch

# 이 코드는 CUDA가 사용 가능한 환경에서만 실행합니다.
# ``torch.device`` 를 사용하여 tensor를 GPU 안팎으로 이동해보겠습니다.

x = torch.rand(4,4)
if torch.cuda.is_available():
    device = "cuda:0" # torch.device("cuda:0")          # CUDA 장치 객체(device object)로
    y = torch.ones_like(x, device=device)  # GPU 상에 직접적으로 tensor를 생성하거나
    print(y)


    x = x.to(device)                       # ``.to("cuda")`` 를 사용하면 됩니다.
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 는 dtype도 함께 변경합니다!

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], device='cuda:0')
tensor([[1.4512, 1.0800, 1.8194, 1.3981],
        [1.3423, 1.5176, 1.6927, 1.8044],
        [1.6748, 1.4634, 1.7604, 1.0744],
        [1.3394, 1.9641, 1.3050, 1.7403]], device='cuda:0')
tensor([[1.4512, 1.0800, 1.8194, 1.3981],
        [1.3423, 1.5176, 1.6927, 1.8044],
        [1.6748, 1.4634, 1.7604, 1.0744],
        [1.3394, 1.9641, 1.3050, 1.7403]], dtype=torch.float64)


In [23]:
x = x.cuda()