# 선형 시스템 실습

In [1]:
import numpy as np

## 행렬과 벡터

In [19]:
A = np.array([[3, 1, 1], [1, -2, 1], [2, -4, 1]])
B = np.array([[2], [3], [6]])

print('A')
print(A)
print(A.shape)

print('\nB')
print(B)
print(B.shape)


A
[[ 3  1  1]
 [ 1 -2  1]
 [ 2 -4  1]]
(3, 3)

B
[[2]
 [3]
 [6]]
(3, 1)


## 역행렬

### 역행렬 구하기

In [20]:
A_inv = np.linalg.inv(A)

print(A_inv)
print(A_inv.shape)

[[ 0.28571429 -0.71428571  0.42857143]
 [ 0.14285714  0.14285714 -0.28571429]
 [ 0.          2.         -1.        ]]
(3, 3)


### 역행렬을 통한 Ax = b의 해

In [21]:
x = np.matmul(A_inv, B)

print('x')
print(x)
print(x.shape)

x
[[ 1.]
 [-1.]
 [ 0.]]
(3, 1)


### 검산

In [22]:
b2 = np.matmul(A, x)

print(b2)
print(b2.shape)

if np.linalg.norm(B - b2) < 1e-3 :
    print('O')
else :
    print('X')

[[2.]
 [3.]
 [6.]]
(3, 1)
O
