In [1]:
import numpy as np

# 선형대수

## 기초

### 영벡터
  - 원소가 모두 0인 벡터
  - `np.zeros(dim)`

In [6]:
print(np.zeros(3))
print()
print(np.zeros((3,2)))
print()
print(np.zeros((3,3,3)))

[0. 0. 0.]

[[0. 0.]
 [0. 0.]
 [0. 0.]]

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


### 일벡터
  - 원소가 모두 1인 벡터
  - `np.ones(dim)`

In [7]:
print(np.ones((2,2)))

[[1. 1.]
 [1. 1.]]


### 대각행렬(diagonal matrix)
  - Main diagonal을 제외한 나머지가 0인 행렬
  - `np.diag((main_diag))`

In [9]:
print(np.diag([2,4]))
print()
print(np.diag([1,3,4]))

[[2 0]
 [0 4]]

[[1 0 0]
 [0 3 0]
 [0 0 4]]


### 항등행렬(identity matrix)
  - main diagonal이 1인 행렬
  - `np.eye(size, (dtype=int, uint, float, complex, ...))`

In [11]:
print(np.eye(2, dtype=int))

[[1 0]
 [0 1]]


In [13]:
print(np.eye(4, dtype=float))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 행렬 곱(dot product)
  - 행렬간의 곱 연산
  - `np.dot()` or `@`
    - `m1.dot(m2)` = `m1 @ m2`

In [17]:
'''
m1 = 1 4
     2 3
     
m2 = 7 9
     0 6
'''

m1 = np.array([[1,4], [2,3]])
m2 = np.array([[7,9], [0,6]])

In [15]:
m1.dot(m2)

array([[ 7, 33],
       [14, 36]])

In [16]:
m1 @ m2

array([[ 7, 33],
       [14, 36]])

## 심화

### 트레이스(trace)
  - Main diagonal의 합
  - `np.trace()`

In [24]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
B = np.eye(3, dtype=int)

In [25]:
print(np.trace(A))
print(A.trace())
print(B.trace())

15
15
3


### 행렬식(determinant)
  - 행렬의 대표값 중 하나
  - 선형변환 과정에서 벡터의 스케일링 척도
  - ![image](image/1.png)
  - `np.linalg.det()`

In [26]:
arr2 = np.array([[1,3], 
                 [2,6]])
arr3 = np.array([[1,4,7], 
                 [2,5,8], 
                 [3,6,9]])

In [27]:
print(np.linalg.det(arr2))
print(np.linalg.det(arr3))

0.0
0.0


### 역행렬
  - 행렬 A에 대해 AB = BA = I를 만족하는 행렬 B = A<sup>-1</sup>
  - `np.linalg.inv()`

In [28]:
A = np.array([[2,1], 
              [4,3]])

In [31]:
A_inv = np.linalg.inv(A)

print(A_inv)
print(A @ A_inv)

[[ 1.5 -0.5]
 [-2.   1. ]]
[[1. 0.]
 [0. 1.]]


### 고유값, 고유벡터(eigenvalue, eigenvector)
  - 정방행렬 A에 대해 $ Ax = \lambda x $를 만족하는 $ \lambda $와 x
    - 선형변환 A에 의한 변환 결과가 자기 자신의 상수배가 되는 0이 아닌 벡터
    - $ (A - \lambda I)x = 0 $ → $ \ \textit{det}(A - \lambda I) = 0 $
  - 고유값 : $ \lambda $, 고유벡터 : x
  - `np.linalg.eig()`
    - `return eigvalue, eigvector`

In [32]:
A = np.array([[2, 0, -2], 
              [1, 1, -2], 
              [0, 0,  1]])

In [42]:
_lambda, x = np.linalg.eig(A)
_lambda, x

(array([1., 2., 1.]),
 array([[0.        , 0.70710678, 0.89442719],
        [1.        , 0.70710678, 0.        ],
        [0.        , 0.        , 0.4472136 ]]))

In [45]:
A @ x[:, 0]        # Ax

array([0., 1., 0.])

In [38]:
_lambda[0] * x[:, 0]    #lambda * x

array([0., 1., 0.])

In [84]:
tmp = A - (_lambda * np.eye(3))
tmp.T

array([[ 1.,  1.,  0.],
       [ 0., -1.,  0.],
       [-2., -2.,  0.]])

In [61]:
np.linalg.det(tmp)

0.0

In [88]:
np.linalg.det(tmp @ x)

0.0