In [4]:
import numpy as np

## 벡터와 스칼라 연산

$$ x = \left( \begin{matrix} 1 \\ 2 \\ 3 \end{matrix} \right) \quad c = 5 $$

In [12]:
x = np.array([1, 2, 3])
c = 5

In [14]:
print(' + : {}'.format(x + c))
print(' - : {}'.format(x - c))
print(' * : {}'.format(x * c))
print(' / : {}'.format(x / c))
print(' % : {}'.format(x % c))

 + : [6 7 8]
 - : [-4 -3 -2]
 * : [ 5 10 15]
 / : [0.2 0.4 0.6]
 % : [1 2 3]


## 벡터와 벡터 연산

$$ x = \left( \begin{matrix} 1 \\ 2 \\ 3 \end{matrix} \right) \quad z = \left( \begin{matrix} 3 \\ 20 \\ 7 \end{matrix} \right) $$

In [15]:
x = np.array([1, 2, 3])
z = np.array([3, 20, 7])

In [16]:
print(' + : {}'.format(x + z))
print(' - : {}'.format(x - z))
print(' * : {}'.format(x * z))
print(' / : {}'.format(x / z))
print(' % : {}'.format(x % z))

 + : [ 4 22 10]
 - : [ -2 -18  -4]
 * : [ 3 40 21]
 / : [0.33333333 0.1        0.42857143]
 % : [1 2 3]


## 인덱싱, 슬라이싱

$$ x = \left( \begin{matrix} 1 & 2 & 3 & 4 \\ 5 & 6 & 7 & 8 \\ 9 & 10 & 11 & 12 \end{matrix} \right) $$

In [63]:
x = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])

In [29]:
print('(2,3) : {}'.format(x[2,3]))
print('(0,2) : {}'.format(x[0,2]))

(2,3) : 12
(0,2) : 3


In [31]:
print('[1:] : {}'.format(x[1:]))
print('[:1] : {}'.format(x[:1]))
print('[:] : {}'.format(x[:]))
print('[1:2] : {}'.format(x[1:2]))
print('[:, 2] : {}'.format(x[: ,2]))
print('[:, 2:] : {}'.format(x[: ,2:]))
print('[:, :] : {}'.format(x[: ,:]))
print('[0:2, 1:3] : {}'.format(x[0:2 ,1:3]))

[1:] : [[ 5  6  7  8]
 [ 9 10 11 12]]
[:1] : [[1 2 3 4]]
[:] : [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1:2] : [[5 6 7 8]]
[:, 2] : [ 3  7 11]
[:, 2:] : [[ 3  4]
 [ 7  8]
 [11 12]]
[:, :] : [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0:2, 1:3] : [[2 3]
 [6 7]]


In [33]:
print('[-1] : {}'.format(x[-1]))
print('[::-1] : {}'.format(x[::-1]))
print('[::-1, ::-1] : {}'.format(x[::-1, ::-1]))

[-1] : [ 9 10 11 12]
[::-1] : [[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[::-1, ::-1] : [[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [65]:
print(x.T)
print(x[:, None])

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]


## Broadcasting
  - 기본적으로 같은 타입의 데이터에 대해서만 연산 가능
  - 피연산자가 연산 가능하도록 변환이 가능한 경우 연산 가능

### *M* x *N*, *M* x 1
$$ x = \left( \begin{matrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{matrix} \right) \quad y = \left( \begin{matrix} 2 \\ 4  \\ 8 \end{matrix} \right) $$

In [40]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
y = np.array([[2], [4], [8]])

x + y

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [15, 16, 17]])

### *M* x *N*, 1 x *N*
$$ x = \left( \begin{matrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{matrix} \right) \quad y = \left( \begin{matrix} 2 & 4 & 8 \end{matrix} \right) $$

In [66]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
y = np.array([2, 4, 8])


print(x + y)
print(x * y)

[[ 3  6 11]
 [ 6  9 14]
 [ 9 12 17]]
[[ 2  8 24]
 [ 8 20 48]
 [14 32 72]]


### *M* x 1 , 1 x *N*
$$ x = \left( \begin{matrix} 1 \\ 4 \\ 7 \end{matrix} \right) \quad y = \left( \begin{matrix} 2 & 4 & 8 \end{matrix} \right) $$

In [43]:
x = np.array([[1], [4], [7]])
y = np.array([2, 4, 8])

x + y

array([[ 3,  5,  9],
       [ 6,  8, 12],
       [ 9, 11, 15]])